name: grocery_list_maker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  share: ^2.0.4
  url_launcher: ^6.0.18
  package_info: ^2.0.2

  intl: ^0.17.0
  open_file: ^3.2.1
  get_time_ago: ^1.1.3
  path_provider: ^2.0.8
  google_fonts: 2.2.0
  flutter_svg: ^1.0.3

  cv: ^0.2.6
  pdf: ^3.7.1
  printing: ^5.7.2
  shared_preferences: ^2.0.13

  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3

  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_sqflite
      ref: dart2_3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/
