name: grocery_list_maker
description: A mobile app that allows you to create a grocery list and share it with others.

publish_to: "none"

version: 1.0.1+10

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  share_plus: ^6.0.1
  url_launcher: ^6.1.6
  package_info_plus: ^3.0.1
  talker: ^2.0.0+1

  intl: ^0.17.0
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  r_upgrade: ^0.3.8+2

  open_file_plus: ^3.3.0
  pdf: ^3.8.4
  printing: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  built_value: ^8.4.1
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  copy_with_extension: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.12
  flutter_launcher_icons: ^0.10.0

  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  json_serializable: ^6.5.3
  copy_with_extension_gen: ^4.0.4
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
